### ISSUE TITLE
Container card outline broken in Wizard

### ISSUE THREAD

**Issue by andlbrei** [dnbexperience/eufemia#4308]
## 💥 Regression Report

ViewContainers have a outline even when using `variant="basic"`, which it did not have previously.
This style is overridable with `outline=basic` generally, but not within a Wizard.
<img width="412" alt="bilde" src="https://github.com/user-attachments/assets/27c02a25-a5ac-4bff-aa07-34e06071dfba">

10.55.0 added a style for nested cards, which might be the culprit.
https://github.com/dnbexperience/eufemia/pull/4244

## Last working version

Worked up to version: 10.54

Stopped working in version: 10.55

## To Reproduce

https://codesandbox.io/p/sandbox/optimistic-https-6kffvm

## Expected behavior
I expect Container components to not have an outline when setting `variant="basic"`.

**Comment by langz** [comment]
Probably related to https://github.com/dnbexperience/eufemia/pull/4244 🤔

**Comment by tujoworker** [comment]
Yes, I think too that we did not catch the change in the visual snapshot. But it is fixed in the main branch already.

**Comment by tujoworker** [comment]
This is fixed and released in v10.57 – here is an [example](https://eufemia.dnb.no/uilib/extensions/forms/Form/Section/demos/#show-errors-on-the-whole-section) (the second one).

**Comment by andlbrei** [comment]
@tujoworker @langz This is still an issue in version 10.57.0
![bilde](https://github.com/user-attachments/assets/ec9cea71-dba7-4f4e-a6bb-a23b95b41c6e)

**Comment by andlbrei** [comment]
Not sure if 10.57.1 was supposed to fix it, or if this was automagically sent by mistake, but it's still not fixed 😅

**Comment by langz** [comment]
We hope that this is now fixed, once and for all, in [v10.58.0](https://github.com/dnbexperience/eufemia/releases/tag/v10.58.0) 🙏
